# Generated by Django 4.1.6 on 2023-09-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files')),
                ('sentiment', models.CharField(max_length=10)),
                ('suggestions', models.TextField()),
            ],
        ),
    ]
