# Generated by Django 4.1.6 on 2023-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_audioentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioentry',
            name='transcript',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='audioentry',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='audioentry',
            name='suggestions',
            field=models.TextField(default=''),
        ),
    ]
